/**
 * Industry-level registration service definitions for Shree Chamunda Associates.
 * Each service maps to a dedicated /services/:slug page.
 */

const registrationServices = [
  {
    title: 'Government Registration',
    slug: 'government-registration',
    description: 'Complete government registration services for businesses — from entity setup to statutory licenses and compliance certificates.',
    icon: '/assets/bookkepping-2.svg',
    link: '/services/government-registration',
    order: 11,
    isActive: true,
    serviceType: 'registration',
    timeline: '7-15 working days',
    governmentFee: 2500,
    professionalFee: 4500,
    detailedOverview:
      'Government Registration encompasses all mandatory statutory registrations required to legally operate a business in India. Whether you are launching a new venture or formalizing an existing one, Shree Chamunda Associates handles end-to-end registration with central and state authorities — including entity incorporation, trade licenses, shop & establishment registration, and professional tax enrollment. Our team ensures every application is filed correctly the first time, minimizing rejections and delays.',
    eligibility: [
      'Individuals or entities starting a new business in India',
      'Existing unregistered businesses seeking legal compliance',
      'Freelancers and professionals requiring trade licenses',
      'Retail shops, restaurants, and service establishments',
      'Manufacturing units requiring factory/establishment licenses',
    ],
    keyBenefits: [
      'Legal recognition to operate your business without penalties',
      'Eligibility for government tenders and MSME benefits',
      'Smooth opening of business bank accounts',
      'Protection against local authority inspections and fines',
      'Foundation for GST, PF, and other statutory registrations',
    ],
    processSteps: [
      { step: 1, title: 'Consultation & Document Review', description: 'We assess your business type, location, and applicable registrations. You receive a customized checklist of required documents.' },
      { step: 2, title: 'Application Preparation', description: 'Our team prepares and verifies all application forms, affidavits, and supporting documents per the relevant authority guidelines.' },
      { step: 3, title: 'Online / Offline Filing', description: 'Applications are submitted to the Municipal Corporation, Labour Department, or relevant state portal with proper fee payment.' },
      { step: 4, title: 'Inspection & Verification', description: 'We coordinate site inspections (if required) and respond to any queries raised by the registering authority.' },
      { step: 5, title: 'Certificate Delivery', description: 'Upon approval, we deliver your registration certificates and guide you on renewal timelines and ongoing compliance.' },
    ],
    documentsRequired: [
      'Aadhaar & PAN of proprietor/directors',
      'Passport-size photographs',
      'Business address proof (rent agreement + NOC from owner)',
      'Utility bill of registered office (not older than 2 months)',
      'Partnership deed / COI (if applicable)',
      'Identity proof of all partners/directors',
      'Nature of business declaration',
    ],
    deliverables: [
      'Shop & Establishment Registration Certificate',
      'Trade License (if applicable)',
      'Professional Tax Enrollment Certificate',
      'Compliance calendar with renewal dates',
      'Digital copies of all approved certificates',
    ],
    faqs: [
      { question: 'Which government registrations are mandatory for a new shop?', answer: 'At minimum, most businesses need Shop & Establishment registration under the state Shops Act, a trade license from the local municipality, and Professional Tax registration. Manufacturing units may additionally require factory licenses.' },
      { question: 'Can I operate without government registration?', answer: 'Operating without required registrations exposes you to penalties, closure notices, and inability to open business bank accounts or claim input tax credits. We strongly recommend completing all applicable registrations before commencing operations.' },
      { question: 'How long does government registration take in Gujarat?', answer: 'Shop & Establishment registration in Gujarat typically takes 5-7 working days. Trade licenses may take 10-15 days depending on the municipal corporation and whether a site inspection is required.' },
    ],
  },
  {
    title: 'GST Registration',
    slug: 'gst-registration',
    description: 'Fast, hassle-free GSTIN registration with Aadhaar authentication — mandatory for businesses crossing turnover thresholds or engaged in interstate trade.',
    icon: '/assets/bookkepping-2.svg',
    link: '/services/gst-registration',
    order: 12,
    isActive: true,
    serviceType: 'registration',
    timeline: '3-7 working days',
    governmentFee: 0,
    professionalFee: 1999,
    detailedOverview:
      'Goods and Services Tax (GST) registration grants your business a unique 15-digit GSTIN, enabling legal collection and remittance of GST, claiming input tax credit on purchases, and issuing tax-compliant invoices. Shree Chamunda Associates handles the entire GST REG-01 application process on the GST Common Portal — from document compilation and Aadhaar-based e-KYC to responding to department queries and obtaining your GSTIN certificate.',
    eligibility: [
      'Businesses with annual turnover exceeding ₹40 Lakhs (goods) or ₹20 Lakhs (services)',
      'Inter-state suppliers regardless of turnover',
      'E-commerce sellers on Amazon, Flipkart, Meesho, etc.',
      'Casual taxable persons and non-resident taxable persons',
      'Input Service Distributors and agents of suppliers',
    ],
    keyBenefits: [
      'Legal interstate and intrastate sales with GST invoices',
      'Claim input tax credit (ITC) on business purchases',
      'Enhanced credibility with B2B clients and government tenders',
      'Mandatory for e-commerce marketplace listings',
      'Avoid penalties up to 100% of tax due for non-registration',
    ],
    processSteps: [
      { step: 1, title: 'Document Collection', description: 'Gather PAN, Aadhaar, address proof, bank details, and business constitution documents as per your entity type.' },
      { step: 2, title: 'Part-A Filing (TRN Generation)', description: 'We file Part-A of Form GST REG-01 on the GST portal to generate your Temporary Reference Number (TRN).' },
      { step: 3, title: 'Part-B & Document Upload', description: 'Complete Part-B with business details, authorized signatory info, and upload scanned documents in prescribed formats.' },
      { step: 4, title: 'Aadhaar Authentication', description: 'Proprietor/directors complete Aadhaar OTP verification. Biometric verification is scheduled only if flagged by the system.' },
      { step: 5, title: 'GSTIN Allotment', description: 'Upon approval, your GSTIN certificate (REG-06) is issued. We configure your first return filing calendar.' },
    ],
    documentsRequired: [
      'PAN card of business/proprietor',
      'Aadhaar card of authorized signatory',
      'Proof of business address (electricity bill + rent agreement + NOC)',
      'Bank account proof (cancelled cheque or statement)',
      'Certificate of Incorporation / Partnership deed (if applicable)',
      'Board resolution / authorization letter for signatory',
      'Digital photograph of proprietor/director',
    ],
    deliverables: [
      'GSTIN Certificate (Form REG-06)',
      'Login credentials for GST portal',
      'GST registration acknowledgment',
      'First-year return filing schedule',
      'Invoice format template with GST fields',
    ],
    faqs: [
      { question: 'Is GST registration free?', answer: 'Yes, there is no government fee for GST registration. Our professional fee covers document preparation, portal filing, Aadhaar authentication support, and query resolution.' },
      { question: 'Can I register for GST voluntarily below the threshold?', answer: 'Absolutely. Voluntary registration is common for startups wanting to claim ITC, sell on e-commerce platforms, or appear more credible to corporate clients.' },
      { question: 'What happens after GST registration?', answer: 'You must file GSTR-1 (outward supplies) and GSTR-3B (summary return with tax payment) monthly or quarterly based on your turnover. We offer ongoing GST return filing services.' },
    ],
  },
  {
    title: 'Import Export Code Registration',
    slug: 'import-export-code-registration',
    description: 'Obtain your 10-digit IEC code from DGFT for legal import and export of goods and services from India.',
    icon: '/assets/bookkepping-2.svg',
    link: '/services/import-export-code-registration',
    order: 13,
    isActive: true,
    serviceType: 'registration',
    timeline: '2-5 working days',
    governmentFee: 500,
    professionalFee: 2499,
    detailedOverview:
      'The Import Export Code (IEC) is a 10-digit identification number issued by the Directorate General of Foreign Trade (DGFT), mandatory for any business or individual importing or exporting goods and services from India. Without an IEC, customs clearance is impossible. Shree Chamunda Associates manages the complete online application on the DGFT portal — including entity verification, document upload, fee payment, and IEC certificate download.',
    eligibility: [
      'Businesses importing raw materials or finished goods',
      'Exporters of goods, software, or services',
      'Manufacturers seeking global market access',
      'E-commerce exporters shipping products abroad',
      'Individuals engaged in international trade (with valid PAN)',
    ],
    keyBenefits: [
      'Mandatory for customs clearance at ports and airports',
      'Avail export incentives under MEIS/RoDTEP schemes',
      'Open foreign currency accounts with banks',
      'Participate in international trade fairs and exhibitions',
      'Lifetime validity — no renewal required (updated annually)',
    ],
    processSteps: [
      { step: 1, title: 'Entity Verification', description: 'We verify your PAN, entity type, and bank details against DGFT requirements before initiating the application.' },
      { step: 2, title: 'Online Application Filing', description: 'Application is filed on the DGFT portal with business details, NIC codes, and authorized person information.' },
      { step: 3, title: 'Document Upload & Fee Payment', description: 'Required documents are uploaded in prescribed format and government fee of ₹500 is paid online.' },
      { step: 4, title: 'DGFT Processing', description: 'DGFT verifies the application. We monitor status and respond to any clarification requests promptly.' },
      { step: 5, title: 'IEC Certificate Issuance', description: 'Your 10-digit IEC is generated and the certificate is downloaded. We guide you on AD code registration with customs.' },
    ],
    documentsRequired: [
      'PAN card of individual/firm/company',
      'Aadhaar card of applicant/proprietor',
      'Cancelled cheque or bank certificate',
      'Proof of business address',
      'Certificate of Incorporation (for companies/LLPs)',
      'Partnership deed (for partnership firms)',
      'Digital photograph and signature',
    ],
    deliverables: [
      '10-digit IEC certificate from DGFT',
      'IEC registration acknowledgment',
      'AD code registration guidance for customs',
      'Export documentation checklist',
      'DGFT portal login assistance',
    ],
    faqs: [
      { question: 'Is IEC required for services export only?', answer: 'Yes, IEC is mandatory even if you export only services (IT, consulting, etc.) and not physical goods. However, individuals exporting services for personal use may be exempt in certain cases.' },
      { question: 'Does IEC need renewal?', answer: 'IEC has lifetime validity but must be updated annually on the DGFT portal between April-June. Failure to update may lead to deactivation.' },
      { question: 'Can a proprietorship get IEC?', answer: 'Yes, proprietorships, partnerships, LLPs, and companies can all obtain IEC using their respective PAN numbers.' },
    ],
  },
  {
    title: 'Startup-India Registration',
    slug: 'startup-india-registration',
    description: 'Get DPIIT Startup India recognition — unlock tax holidays, IPR fee rebates, self-certification compliance, and easier funding access.',
    icon: '/assets/bookkepping-2.svg',
    link: '/services/startup-india-registration',
    order: 14,
    isActive: true,
    serviceType: 'registration',
    timeline: '5-10 working days',
    governmentFee: 0,
    professionalFee: 3499,
    detailedOverview:
      'Startup India is the Government of India\'s flagship initiative to build a robust startup ecosystem. DPIIT (Department for Promotion of Industry and Internal Trade) recognition grants your startup access to a 3-year income tax holiday under Section 80-IAC, 80% rebate on patent/trademark fees, self-certification under 6 labour and 3 environment laws, and fast-track patent examination. Shree Chamunda Associates prepares your pitch deck summary, innovation narrative, and DPIIT application to maximize approval chances.',
    eligibility: [
      'Entity incorporated as Private Limited, LLP, or Registered Partnership',
      'Age of entity not exceeding 10 years from date of incorporation',
      'Annual turnover not exceeding ₹100 Crores in any financial year',
      'Working towards innovation, development, or improvement of products/processes',
      'Not formed by splitting or reconstructing an existing business',
    ],
    keyBenefits: [
      '3-year tax holiday under Section 80-IAC (subject to approval)',
      '80% rebate on patent filing fees and 50% on trademark fees',
      'Self-certification compliance under labour and environment laws',
      'Exemption from prior experience/turnover criteria in government tenders',
      'Access to Fund of Funds for Startups (FFS) and SIDBI schemes',
    ],
    processSteps: [
      { step: 1, title: 'Eligibility Assessment', description: 'We verify your entity type, age, turnover, and innovation criteria against DPIIT guidelines.' },
      { step: 2, title: 'Innovation Narrative Preparation', description: 'Our team drafts the innovation description, business model summary, and scalability statement required by DPIIT.' },
      { step: 3, title: 'DPIIT Portal Registration', description: 'Application is filed on the Startup India portal with entity details, director info, and supporting documents.' },
      { step: 4, title: 'Certificate of Recognition', description: 'Upon approval, DPIIT issues the Startup Recognition Certificate with your unique recognition number.' },
      { step: 5, title: 'Post-Recognition Advisory', description: 'We guide you on applying for Section 80-IAC tax exemption and availing IPR fee concessions.' },
    ],
    documentsRequired: [
      'Certificate of Incorporation / LLP Agreement',
      'PAN card of entity',
      'Brief write-up on innovation and business model',
      'Website link or pitch deck (if available)',
      'Directors/partners list with Aadhaar and PAN',
      'Proof of concept or prototype details (recommended)',
      'Authorization letter for applicant',
    ],
    deliverables: [
      'DPIIT Startup Recognition Certificate',
      'Startup India portal profile setup',
      'Section 80-IAC application guidance',
      'IPR fee concession application support',
      'Compliance self-certification templates',
    ],
    faqs: [
      { question: 'Is Startup India registration the same as company registration?', answer: 'No. Company registration (via MCA) creates your legal entity. Startup India recognition is an additional DPIIT certification that unlocks startup-specific benefits for eligible entities.' },
      { question: 'Can a sole proprietorship get Startup India recognition?', answer: 'No. Only Private Limited Companies, LLPs, and Registered Partnership Firms are eligible for DPIIT recognition.' },
      { question: 'How long is the tax holiday valid?', answer: 'Approved startups can claim 100% deduction on profits for 3 consecutive years out of 10 years since incorporation, under Section 80-IAC.' },
    ],
  },
  {
    title: 'Udhyam-MSME Registration',
    slug: 'udhyam-msme-registration',
    description: 'Free Udyam MSME registration for micro, small, and medium enterprises — unlock collateral-free loans, subsidies, and tender preferences.',
    icon: '/assets/bookkepping-2.svg',
    link: '/services/udhyam-msme-registration',
    order: 15,
    isActive: true,
    serviceType: 'registration',
    timeline: '1-3 working days',
    governmentFee: 0,
    professionalFee: 999,
    detailedOverview:
      'Udyam Registration (formerly Udyog Aadhaar) is the official MSME registration on the Udyam portal, based entirely on self-declaration with Aadhaar and PAN verification. Registered MSMEs gain access to collateral-free loans under CGTMSE, lower interest rates, protection against delayed payments (45-day rule), electricity tariff concessions, and exclusive reservation in government procurement. Shree Chamunda Associates handles Aadhaar OTP verification, NIC code selection, and Udyam certificate generation.',
    eligibility: [
      'Micro: Investment ≤ ₹1 Cr and turnover ≤ ₹5 Cr',
      'Small: Investment ≤ ₹10 Cr and turnover ≤ ₹50 Cr',
      'Medium: Investment ≤ ₹50 Cr and turnover ≤ ₹250 Cr',
      'Proprietorships, partnerships, LLPs, and companies',
      'Both manufacturing and service enterprises',
    ],
    keyBenefits: [
      'Collateral-free bank loans up to ₹2 Crores under CGTMSE',
      '1% exemption on interest rate on OD (as per RBI guidelines)',
      'Protection against delayed payments beyond 45 days',
      '50% subsidy on patent registration fees',
      'Priority sector lending and ISO certification reimbursement',
    ],
    processSteps: [
      { step: 1, title: 'Classification Assessment', description: 'We determine your MSME category (Micro/Small/Medium) based on investment in plant & machinery and annual turnover.' },
      { step: 2, title: 'Aadhaar & PAN Verification', description: 'Proprietor\'s Aadhaar is verified via OTP. PAN of entity is validated against IT records automatically.' },
      { step: 3, title: 'Udyam Portal Filing', description: 'Application is filed on udyamregistration.gov.in with NIC code, activity details, and investment/turnover declarations.' },
      { step: 4, title: 'Certificate Generation', description: 'Udyam Registration Certificate with QR code and unique Udyam Number is generated instantly upon successful filing.' },
      { step: 5, title: 'Benefit Activation Guide', description: 'We provide guidance on availing CGTMSE loans, updating Udyam annually, and linking with GSTIN.' },
    ],
    documentsRequired: [
      'Aadhaar number of proprietor/authorized signatory',
      'PAN of individual (proprietorship) or entity (company/LLP)',
      'GSTIN (if registered — auto-fetched)',
      'Bank account number and IFSC',
      'NIC code for business activity',
      'Investment and turnover self-declaration',
    ],
    deliverables: [
      'Udyam Registration Certificate with QR code',
      'Unique Udyam Registration Number (URN)',
      'MSME classification confirmation',
      'CGTMSE loan application guidance',
      'Annual update reminder setup',
    ],
    faqs: [
      { question: 'Is Udyam registration really free?', answer: 'Yes, the government charges zero fee for Udyam registration. Our fee covers NIC code selection, portal filing, Aadhaar OTP assistance, and post-registration advisory.' },
      { question: 'Can I register without GST?', answer: 'Yes, GST registration is not mandatory for Udyam registration. However, if you have a GSTIN, it is auto-linked and simplifies verification.' },
      { question: 'Do I need to renew Udyam registration?', answer: 'No renewal is required, but you must update your Udyam registration if your enterprise is reclassified (e.g., from Micro to Small) due to increased investment or turnover.' },
    ],
  },
  {
    title: 'Professional Tax Registration',
    slug: 'professional-tax-registration',
    description: 'Mandatory Professional Tax enrollment and registration for employers and professionals in applicable states including Gujarat.',
    icon: '/assets/bookkepping-2.svg',
    link: '/services/professional-tax-registration',
    order: 16,
    isActive: true,
    serviceType: 'registration',
    timeline: '3-7 working days',
    governmentFee: 500,
    professionalFee: 1499,
    detailedOverview:
      'Professional Tax (PT) is a state-level tax levied on professions, trades, and employment. In Gujarat, every employer with salaried employees and every professional (CA, doctor, lawyer, consultant) must obtain Professional Tax Enrollment (PTEC) and Registration (PTRC) certificates. Non-compliance attracts penalties up to ₹5,000 per month. Shree Chamunda Associates handles enrollment on the Gujarat commercial tax portal, EC registration, and monthly PT return setup.',
    eligibility: [
      'Employers with one or more salaried employees in Gujarat',
      'Self-employed professionals earning above threshold',
      'Companies, LLPs, and partnership firms with employees',
      'Contractors and traders with salaried staff',
      'Branches operating in multiple PT-applicable states',
    ],
    keyBenefits: [
      'Legal compliance with state Professional Tax Act',
      'Avoid penalties and prosecution for non-registration',
      'Smooth payroll processing with PT deductions',
      'Required for government and corporate vendor empanelment',
      'Enables PT return filing and certificate generation',
    ],
    processSteps: [
      { step: 1, title: 'Applicability Check', description: 'We determine whether you need PTEC (employer enrollment), PTRC (employer registration), or both based on your entity and employee count.' },
      { step: 2, title: 'Portal Registration', description: 'Entity is registered on the Gujarat Professional Tax portal with PAN, address, and business details.' },
      { step: 3, title: 'Certificate Application', description: 'Enrollment and registration applications are filed with applicable government fees.' },
      { step: 4, title: 'EC Generation', description: 'Electronic Certificate (EC) is generated upon approval with your PT registration number.' },
      { step: 5, title: 'Return Filing Setup', description: 'We configure monthly PT return filing schedule and employee PT slab calculations.' },
    ],
    documentsRequired: [
      'PAN card of entity',
      'Certificate of Incorporation / registration proof',
      'Address proof of business premises',
      'List of employees with salary details',
      'Bank account details',
      'Authorized signatory Aadhaar and PAN',
      'GSTIN certificate (if available)',
    ],
    deliverables: [
      'Professional Tax Enrollment Certificate (PTEC)',
      'Professional Tax Registration Certificate (PTRC)',
      'EC (Electronic Certificate) from commercial tax dept.',
      'Monthly PT return filing calendar',
      'Employee PT deduction slab chart',
    ],
    faqs: [
      { question: 'What is the Professional Tax rate in Gujarat?', answer: 'For employees, PT ranges from ₹0 to ₹200 per month based on salary slabs (max ₹2,500/year). Employers pay a flat ₹2,500/year enrollment fee under PTEC.' },
      { question: 'Is PT applicable to freelancers?', answer: 'Self-employed professionals like CAs, doctors, and lawyers must enroll under PTEC and pay the annual professional tax in applicable states including Gujarat.' },
      { question: 'How often are PT returns filed?', answer: 'Professional Tax returns are filed monthly in Gujarat, with annual payment of tax deducted from employees\' salaries.' },
    ],
  },
  {
    title: 'PAN Application',
    slug: 'pan-application',
    description: 'New PAN card application or correction for individuals, HUFs, companies, and firms — essential for all financial and tax transactions.',
    icon: '/assets/bookkepping-2.svg',
    link: '/services/pan-application',
    order: 17,
    isActive: true,
    serviceType: 'registration',
    timeline: '7-15 working days',
    governmentFee: 107,
    professionalFee: 499,
    detailedOverview:
      'Permanent Account Number (PAN) is a 10-character alphanumeric identifier issued by the Income Tax Department, mandatory for filing income tax returns, opening bank accounts, high-value transactions, and business registrations. Shree Chamunda Associates handles new PAN applications (Form 49A for Indian citizens, 49AA for foreigners) and PAN correction/reprint requests through NSDL or UTIITSL — with document verification, online filing, and status tracking until card delivery.',
    eligibility: [
      'Indian citizens without an existing PAN',
      'NRIs requiring PAN for property or investment in India',
      'Minors (applied by parent/guardian)',
      'Companies, LLPs, firms, and trusts needing entity PAN',
      'Individuals requiring PAN correction (name, DOB, address)',
    ],
    keyBenefits: [
      'Mandatory for income tax return filing',
      'Required for bank account opening and DEMAT accounts',
      'Needed for property transactions above ₹10 Lakhs',
      'Essential for GST, TAN, and business registrations',
      'Serves as universal identity proof for financial transactions',
    ],
    processSteps: [
      { step: 1, title: 'Application Type Selection', description: 'We determine the correct form (49A/49AA) and category (individual, company, HUF, etc.) for your application.' },
      { step: 2, title: 'Document Preparation', description: 'Identity proof, address proof, and date of birth proof are verified and scanned as per NSDL/UTIITSL specifications.' },
      { step: 3, title: 'Online Application Filing', description: 'Application is filed online with accurate details. Acknowledgment number is generated for tracking.' },
      { step: 4, title: 'Document Dispatch / e-KYC', description: 'Physical documents are dispatched to NSDL/UTIITSL (if required) or Aadhaar-based e-KYC is completed for instant processing.' },
      { step: 5, title: 'PAN Card Delivery', description: 'PAN is allotted and e-PAN is emailed. Physical card is dispatched to your registered address within 15-20 days.' },
    ],
    documentsRequired: [
      'Proof of Identity (Aadhaar, passport, voter ID, driving license)',
      'Proof of Address (Aadhaar, utility bill, bank statement)',
      'Proof of Date of Birth (birth certificate, matriculation certificate)',
      'Passport-size photograph (for physical card)',
      'COI / registration certificate (for entities)',
      'Signed application form (Form 49A/49AA)',
    ],
    deliverables: [
      'PAN allotment letter',
      'e-PAN PDF via email',
      'Physical PAN card (dispatched by NSDL/UTIITSL)',
      'Application acknowledgment with tracking number',
      'PAN verification on IT portal',
    ],
    faqs: [
      { question: 'How long does a new PAN take?', answer: 'With Aadhaar-based e-KYC, PAN is often allotted within 2-4 days. Physical card delivery takes an additional 10-15 days. Without e-KYC, processing takes 15-20 working days.' },
      { question: 'Can I have two PAN cards?', answer: 'No. Holding more than one PAN is illegal and punishable with a fine up to ₹10,000. If you have duplicate PANs, we assist with surrender proceedings.' },
      { question: 'Is PAN required for minors?', answer: 'PAN is not mandatory for minors unless they have taxable income. However, many parents apply for PAN early for investment in the child\'s name.' },
    ],
  },
  {
    title: 'TAN Application',
    slug: 'tan-application',
    description: 'Tax Deduction and Collection Account Number (TAN) application for businesses deducting TDS on salary, rent, professional fees, and payments.',
    icon: '/assets/bookkepping-2.svg',
    link: '/services/tan-application',
    order: 18,
    isActive: true,
    serviceType: 'registration',
    timeline: '5-10 working days',
    governmentFee: 65,
    professionalFee: 799,
    detailedOverview:
      'Tax Deduction and Collection Account Number (TAN) is a 10-digit alphanumeric number required by every person who deducts or collects tax at source (TDS/TCS). Without TAN, TDS returns cannot be filed and penalties of ₹10,000 apply. Shree Chamunda Associates handles Form 49B application through NSDL, ensuring accurate category selection, address details, and timely TAN allotment for your business.',
    eligibility: [
      'Employers deducting TDS on employee salaries',
      'Businesses paying rent exceeding ₹50,000/month',
      'Companies deducting TDS on professional/contractor fees',
      'Buyers deducting TDS on property purchases (Section 194-IA)',
      'Any entity required to deduct or collect tax at source',
    ],
    keyBenefits: [
      'Mandatory for filing quarterly TDS returns (24Q, 26Q, 27Q)',
      'Enables generation of TDS certificates (Form 16/16A)',
      'Avoid penalty of ₹10,000 for failure to obtain TAN',
      'Required for depositing TDS through Challan 281',
      'Essential for government and corporate vendor payments',
    ],
    processSteps: [
      { step: 1, title: 'Requirement Assessment', description: 'We identify all TDS sections applicable to your business (salary, rent, professional fees, etc.).' },
      { step: 2, title: 'Form 49B Preparation', description: 'Application is prepared with entity details, category of deductor, and communication address.' },
      { step: 3, title: 'NSDL Portal Filing', description: 'Form 49B is filed online on the NSDL TAN portal with government fee payment of ₹65 (including GST).' },
      { step: 4, title: 'TAN Allotment', description: 'NSDL processes the application and allots TAN, communicated via email and postal letter.' },
      { step: 5, title: 'TRACES Registration', description: 'We assist with TRACES portal registration for TDS return filing and Form 16/16A generation.' },
    ],
    documentsRequired: [
      'PAN card of entity',
      'Certificate of Incorporation / registration proof',
      'Address proof of registered office',
      'Authorized signatory proof (Aadhaar/PAN)',
      'Contact details (email and mobile)',
      'Business activity description',
    ],
    deliverables: [
      'TAN allotment letter from NSDL',
      'TAN confirmation on IT portal',
      'TRACES portal registration assistance',
      'TDS return filing calendar (24Q/26Q/27Q)',
      'Challan 281 payment guide',
    ],
    faqs: [
      { question: 'Is TAN different from PAN?', answer: 'Yes. PAN identifies the entity for income tax purposes. TAN is specifically for tax deduction/collection at source. A business needs both — PAN for its own taxes and TAN for deducting TDS on payments.' },
      { question: 'Can I use PAN instead of TAN for TDS?', answer: 'No. Quoting PAN instead of TAN in TDS statements attracts a penalty of ₹10,000 under Section 272BB.' },
      { question: 'How many TANs can one entity have?', answer: 'Generally one TAN per entity suffices. However, if a company has branches in different cities doing independent TDS, separate TANs may be required for each branch.' },
    ],
  },
  {
    title: 'ESI Registration',
    slug: 'esi-registration',
    description: 'Employees\' State Insurance (ESI) registration for establishments with 10+ employees — medical and social security coverage for workers.',
    icon: '/assets/bookkepping-2.svg',
    link: '/services/esi-registration',
    order: 19,
    isActive: true,
    serviceType: 'registration',
    timeline: '7-12 working days',
    governmentFee: 0,
    professionalFee: 2499,
    detailedOverview:
      'Employees\' State Insurance (ESI) is a self-financing social security scheme providing medical, sickness, maternity, disability, and dependent benefits to employees earning up to ₹21,000/month. Establishments with 10 or more employees (20 in some states) must register with ESIC. Shree Chamunda Associates handles employer registration on the ESIC portal, code number allotment, employee enrollment, and monthly contribution return setup.',
    eligibility: [
      'Factories and establishments with 10+ employees (Gujarat threshold)',
      'Employees earning gross wages up to ₹21,000/month',
      'Shops, hotels, restaurants, and cinemas',
      'Road transport establishments',
      'Private medical and educational institutions',
    ],
    keyBenefits: [
      'Medical care for insured employees and dependents',
      'Sickness benefit at 70% of wages for 91 days/year',
      'Maternity benefit for 26 weeks (full wage)',
      'Disability and dependent benefits',
      'Unemployment allowance under Rajiv Gandhi Shramik Kalyan Yojana',
    ],
    processSteps: [
      { step: 1, title: 'Applicability Review', description: 'We verify employee count, wage limits, and whether your establishment falls under ESI-covered areas in Gujarat.' },
      { step: 2, title: 'Employer Registration', description: 'Employer registration is filed on esic.in with business details, PAN, bank info, and employee count.' },
      { step: 3, title: 'Code Number Allotment', description: 'ESIC allots a 17-digit employer code number upon verification of application.' },
      { step: 4, title: 'Employee Enrollment', description: 'Each eligible employee is enrolled with IP number, photograph, and family details on the ESIC portal.' },
      { step: 5, title: 'Monthly Return Setup', description: 'We configure monthly contribution returns (MCR) and challan payment schedule — employer contributes 3.25%, employee 0.75%.' },
    ],
    documentsRequired: [
      'PAN card of establishment',
      'Certificate of Incorporation / registration proof',
      'Address proof of factory/establishment',
      'Bank account details with cancelled cheque',
      'List of employees with salary and joining dates',
      'Employee Aadhaar and family details',
      'Registration certificate under Shops & Establishment Act',
    ],
    deliverables: [
      'ESIC employer code number (17-digit)',
      'Employee IP numbers for all enrolled staff',
      'ESIC registration certificate',
      'Monthly contribution return (MCR) filing setup',
      'Pehchan card application for employees',
    ],
    faqs: [
      { question: 'Is ESI mandatory for all businesses?', answer: 'ESI applies to non-seasonal factories with 10+ employees and establishments notified by the state government. In Gujarat, the threshold is 10 employees for most covered establishments.' },
      { question: 'What is the ESI contribution rate?', answer: 'Employer contributes 3.25% and employee contributes 0.75% of gross wages (up to ₹21,000/month wage ceiling). Total ESI contribution is 4% of wages.' },
      { question: 'What if my employee count drops below 10?', answer: 'Once registered, ESI coverage continues even if employee count falls below the threshold. However, new registrations are not required until the threshold is crossed again.' },
    ],
  },
  {
    title: 'Digital Signature',
    slug: 'digital-signature',
    description: 'Class 3 Digital Signature Certificates (DSC) for MCA filings, GST, e-tendering, income tax, and secure document signing.',
    icon: '/assets/bookkepping-2.svg',
    link: '/services/digital-signature',
    order: 20,
    isActive: true,
    serviceType: 'registration',
    timeline: '1-3 working days',
    governmentFee: 0,
    professionalFee: 1500,
    detailedOverview:
      'A Digital Signature Certificate (DSC) is the electronic equivalent of a physical signature, legally valid under the IT Act 2000. Class 3 DSC is required for MCA company filings, income tax e-filing, GST registration, e-tendering on GeM/CPPP, and DGFT applications. Shree Chamunda Associates facilitates DSC application through licensed Certifying Authorities (eMudhra, Capricorn, Sify) with video verification, USB token delivery, and renewal reminders.',
    eligibility: [
      'Directors and shareholders for MCA/ROC filings',
      'Authorized signatories for GST registration',
      'Professionals filing income tax returns for clients',
      'Businesses participating in e-tendering (GeM, CPPP)',
      'Import/export businesses for DGFT portal access',
    ],
    keyBenefits: [
      'Legally valid digital signing of documents and forms',
      'Mandatory for MCA SPICe+ company incorporation',
      'Required for GST, IT, and TDS portal authentication',
      'Enables participation in government e-tenders',
      'Secure, tamper-proof document authentication',
    ],
    processSteps: [
      { step: 1, title: 'DSC Type Selection', description: 'We recommend Class 3 DSC (individual or organization) based on your usage — MCA, GST, e-tender, or multi-purpose.' },
      { step: 2, title: 'Document Collection', description: 'PAN, Aadhaar, and photograph are collected. Organization DSC additionally requires authorization letter and entity proof.' },
      { step: 3, title: 'Online Application & Video KYC', description: 'Application is filed with the Certifying Authority. Applicant completes video verification via mobile or laptop.' },
      { step: 4, title: 'Certificate Issuance', description: 'Upon successful verification, DSC is issued and downloaded onto the USB e-token (Hyper2003 or mToken).' },
      { step: 5, title: 'Installation & Testing', description: 'We assist with DSC driver installation, token setup, and test signing on the relevant portal (MCA, GST, etc.).' },
    ],
    documentsRequired: [
      'PAN card of applicant',
      'Aadhaar card of applicant',
      'Passport-size photograph',
      'Mobile number and email for OTP/video KYC',
      'Organization proof (for organization DSC)',
      'Board resolution / authorization letter (for company DSC)',
      'GSTIN or COI (for organization verification)',
    ],
    deliverables: [
      'Class 3 Digital Signature Certificate on USB token',
      'DSC certificate download backup',
      'Token driver installation support',
      'Portal registration assistance (MCA/GST/IT)',
      'Renewal reminder before expiry (1-2 year validity)',
    ],
    faqs: [
      { question: 'What is the difference between Class 2 and Class 3 DSC?', answer: 'Class 2 DSC has been discontinued since January 2021. Class 3 is now mandatory for all government portal filings including MCA, GST, income tax, and e-tendering.' },
      { question: 'How long is a DSC valid?', answer: 'DSC is typically issued for 1 or 2 years. Renewal requires fresh video KYC. We send reminders 30 days before expiry.' },
      { question: 'Can one DSC be used for multiple portals?', answer: 'Yes. A single Class 3 DSC works across MCA, GST, income tax, TDS, DGFT, and e-tendering portals. Organization DSC covers all authorized signatories of the entity.' },
    ],
  },
];

module.exports = registrationServices;
