
const startupServices = [
  {
    title: 'Private Limited Company',
    slug: 'private-limited-company',
    description: 'Register a Private Limited Company (Pvt Ltd) to secure limited liability, raise venture capital, and build corporate credibility.',
    icon: '/assets/bookkepping-2.svg',
    link: '/services/private-limited-company',
    order: 31,
    isActive: true,
    serviceType: 'startup',
    timeline: '7-10 working days',
    governmentFee: 1500,
    professionalFee: 5500,
    detailedOverview:
      'Private Limited Company incorporation is the most popular corporate legal structure for startups and growing businesses in India. It requires a minimum of 2 directors and offers the ability to dilute shares and raise external equity funding. Shree Chamunda Associates handles SPICe+ MCA filing, name approval, DIN allocation, DSC, PAN, TAN, and Certificate of Incorporation issuance.',
    eligibility: [
      'Minimum 2 Directors (at least one Indian resident)',
      'Minimum 2 Shareholders (can be the same as directors)',
      'A unique name that does not resemble existing companies/trademarks',
    ],
    keyBenefits: [
      'Limited liability protection of personal assets',
      'Separate legal entity status with perpetual succession',
      'Easy transferability of shares and high investor appeal',
    ],
    processSteps: [
      { step: 1, title: 'Name Reservation (RUN)', description: 'We reserve a unique name on the Ministry of Corporate Affairs (MCA) portal.' },
      { step: 2, title: 'DSC Acquisition', description: 'We procure Digital Signature Certificates (DSC) for all directors.' },
      { step: 3, title: 'SPICe+ Form Submission', description: 'We draft and file SPICe+ Part-B, Agile Pro, and e-MOA/AOA forms.' },
      { step: 4, title: 'MCA Approval & PAN/TAN', description: 'MCA verifies the application and issues the Certificate of Incorporation with PAN & TAN.' },
      { step: 5, title: 'Corporate Bank Account', description: 'We assist in opening a zero-balance business current account with partner banks.' },
    ],
    documentsRequired: [
      'PAN Card of all Directors',
      'Aadhaar Card of all Directors',
      'Address Proof of Directors (Bank Statement/Utility bill not older than 2 months)',
      'Registered Office Address Proof (Electricity bill / Property tax receipt)',
      'Rent Agreement & Owner NOC (if office is rented)',
    ],
    deliverables: [
      'Certificate of Incorporation (COI)',
      'Memorandum of Association (MOA)',
      'Articles of Association (AOA)',
      'Company PAN & TAN Cards',
      'Class 3 DSC for 2 Directors',
    ],
    faqs: [
      { question: 'What is the minimum capital required to start a Pvt Ltd?', answer: 'There is no minimum authorized capital requirement. You can start a company with an initial capital of as low as ₹10,000.' },
      { question: 'Is a physical office mandatory for company registration?', answer: 'Yes, but it does not have to be a commercial space. A residential address (like a director\'s home) can serve as the registered office.' },
    ],
  },
  {
    title: 'Limited Liability Partnership Firm',
    slug: 'limited-liability-partnership-firm',
    description: 'Incorporate an LLP to enjoy corporate status with lower compliance requirements compared to companies.',
    icon: '/assets/bookkepping-2.svg',
    link: '/services/limited-liability-partnership-firm',
    order: 32,
    isActive: true,
    serviceType: 'startup',
    timeline: '8-12 working days',
    governmentFee: 1000,
    professionalFee: 4500,
    detailedOverview:
      'An LLP combines the limited liability benefits of a company with the operational flexibility of a traditional partnership. It is ideal for service firms, consulting agencies, and family-owned enterprises. Shree Chamunda Associates drafts the LLP agreement, reserves the name, procures DSC, and files the incorporation form FiLLiP with the MCA.',
    eligibility: [
      'Minimum 2 Designated Partners',
      'A signed LLP Agreement defining profit sharing',
      'Unique name matching MCA guidelines',
    ],
    keyBenefits: [
      'No audit required if turnover is under ₹40 Lakhs and capital is under ₹25 Lakhs',
      'Less compliance cost than a Private Limited Company',
      'Partners are not liable for other partners\' misconduct or negligence',
    ],
    processSteps: [
      { step: 1, title: 'Name Approval (RUN-LLP)', description: 'Reserve a unique name for the LLP on the MCA portal.' },
      { step: 2, title: 'DSC Procurement', description: 'Acquire digital signatures for all designated partners.' },
      { step: 3, title: 'FiLLiP Form Filing', description: 'File the integration incorporation application with MCA.' },
      { step: 4, title: 'LLP Agreement Drafting', description: 'Draft the LLP agreement defining partners rights and duties.' },
      { step: 5, title: 'Agreement Filing (Form 3)', description: 'Submit the signed LLP agreement within 30 days of incorporation.' },
    ],
    documentsRequired: [
      'PAN Card of all Partners',
      'Aadhaar Card of all Partners',
      'Partners Address Proof (Utility bill / Bank statement)',
      'Registered Office utility bill',
      'Rent Agreement & Owner NOC',
    ],
    deliverables: [
      'LLP Incorporation Certificate (Form 16)',
      'Approved LLP Agreement',
      'LLP PAN & TAN Cards',
      'DSC for 2 Partners',
    ],
    faqs: [
      { question: 'Who can be a partner in an LLP?', answer: 'Any individual or body corporate (including a Private Limited Company or foreign company) can become a partner in an LLP.' },
    ],
  },
  {
    title: 'Sole Properties',
    slug: 'sole-proprietorship',
    description: 'Start a Sole Proprietorship business with simple local registrations and a business current account.',
    icon: '/assets/bookkepping-2.svg',
    link: '/services/sole-proprietorship',
    order: 33,
    isActive: true,
    serviceType: 'startup',
    timeline: '2-4 working days',
    governmentFee: 0,
    professionalFee: 1499,
    detailedOverview:
      'Sole Proprietorship is the simplest form of business entity, owned and managed by a single individual. It does not have a separate legal identity, but is quick to start and has the lowest compliance costs. Shree Chamunda Associates sets up your proprietorship using MSME/Udyam and GST registrations to enable opening a business bank account.',
    eligibility: [
      'A single individual who is an Indian citizen and resident',
    ],
    keyBenefits: [
      'Easiest business structure to establish and close',
      'Complete control of all operations and profits by the owner',
      'Minimal annual compliance filings and simple income tax reporting',
    ],
    processSteps: [
      { step: 1, title: 'License Selection', description: 'We select the correct registration license (Udyam, GST, or Shop Act) based on your business.' },
      { step: 2, title: 'Documentation & Filing', description: 'We prepare the applications and upload the proprietor\'s KYC files.' },
      { step: 3, title: 'Certificate Download', description: 'The registration certificates are generated and downloaded.' },
      { step: 4, title: 'Current Account Opening', description: 'We assist with bank documentation to open your business current account.' },
    ],
    documentsRequired: [
      'PAN Card of the Proprietor',
      'Aadhaar Card of the Proprietor',
      'Office Address Proof (Electricity bill / Rent agreement)',
      'Owner NOC (if rented)',
      'Proprietor passport photo',
    ],
    deliverables: [
      'Udyam MSME Certificate',
      'GST Registration Certificate (if applicable)',
      'Business PAN Allocation (same as owner\'s PAN)',
    ],
    faqs: [
      { question: 'Is a separate PAN required for a Sole Proprietorship?', answer: 'No. A proprietorship has no separate legal existence, so the owner\'s personal PAN is used for all business tax filings.' },
    ],
  },
  {
    title: 'Hindu Undividable Family(HUF)',
    slug: 'huf-registration',
    description: 'Set up a HUF entity to legally split tax liability and save taxes on family assets.',
    icon: '/assets/bookkepping-2.svg',
    link: '/services/huf-registration',
    order: 34,
    isActive: true,
    serviceType: 'startup',
    timeline: '5-7 working days',
    governmentFee: 107,
    professionalFee: 2499,
    detailedOverview:
      'Under Hindu Law, a Hindu Undivided Family (HUF) is treated as a separate legal entity for tax purposes. By creating a HUF, families can create an additional tax slab, split their income legally, and minimize tax liability under the Income Tax Act. Shree Chamunda Associates drafts the HUF deed, applies for a HUF PAN, and sets up the HUF bank account.',
    eligibility: [
      'A family consisting of a common ancestor and all lineal descendants (Hindu, Buddhist, Sikh, Jain families)',
    ],
    keyBenefits: [
      'Separate basic tax exemption limit (₹3 Lakhs to ₹7 Lakhs tax-free)',
      'Can own property and carry out business in the HUF name',
      'Enables savings through investments in the HUF name (80C, etc.)',
    ],
    processSteps: [
      { step: 1, title: 'Family Structure Declaration', description: 'We document the family tree containing the Karta and all members.' },
      { step: 2, title: 'HUF Deed Drafting', description: 'We draft the legal HUF declaration deed detailing Karta powers.' },
      { step: 3, title: 'Stamp Paper Execution', description: 'The deed is executed and signed on a stamp paper by all members.' },
      { step: 4, title: 'PAN Application', description: 'We apply for a separate PAN card for the HUF on NSDL.' },
      { step: 5, title: 'HUF Account Setup', description: 'We set up the HUF bank current/savings account.' },
    ],
    documentsRequired: [
      'PAN & Aadhaar of Karta (Head of Family)',
      'Aadhaar Card of all Coparceners (family members)',
      'HUF Declaration Deed on Stamp Paper',
      'Address proof of Karta',
    ],
    deliverables: [
      'HUF Deed Draft',
      'HUF PAN Card',
      'HUF Bank Account Opening kit',
    ],
    faqs: [
      { question: 'Who is a Karta in a HUF?', answer: 'The Karta is the senior member (male or female) of the family who manages the HUF affairs and signs all tax papers.' },
    ],
  },
  {
    title: 'Public Limited Company',
    slug: 'public-limited-company',
    description: 'Register a Public Limited Company to raise capital from the general public and list on stock exchanges.',
    icon: '/assets/bookkepping-2.svg',
    link: '/services/public-limited-company',
    order: 35,
    isActive: true,
    serviceType: 'startup',
    timeline: '12-15 working days',
    governmentFee: 2500,
    professionalFee: 9999,
    detailedOverview:
      'A Public Limited Company requires a minimum of 7 shareholders and 3 directors. It has no restriction on the maximum number of shareholders, making it ideal for large-scale operations seeking public capital. Shree Chamunda Associates handles SPICe+ MCA filing, DIN allocations, digital signatures, name reservation, and incorporation certificates.',
    eligibility: [
      'Minimum 3 Directors',
      'Minimum 7 Shareholders/Subscribers',
      'Unique name ending with "Limited"',
    ],
    keyBenefits: [
      'Ability to raise public equity capital through IPOs',
      'High credibility with financial institutions and global partners',
      'Shares are freely transferable on stock exchanges',
    ],
    processSteps: [
      { step: 1, title: 'Name Reservation (RUN)', description: 'Submit a name reservation request ending with the word "Limited".' },
      { step: 2, title: 'DSC & DIN procurement', description: 'Procure digital signature certificates and Director Identification Numbers (DIN).' },
      { step: 3, title: 'MCA Filing', description: 'File incorporation documents (SPICe+) and e-MOA/AOA forms with MCA.' },
      { step: 4, title: 'COI & PAN/TAN', description: 'The Registrar of Companies issues the COI and corporate tax IDs.' },
    ],
    documentsRequired: [
      'PAN Card of all Directors/Shareholders',
      'Aadhaar Card of all Directors/Shareholders',
      'Identity & Address Proof of Directors (Bank stmt/utility bill)',
      'Registered office address utility bill',
      'Rent agreement & NOC',
    ],
    deliverables: [
      'Certificate of Incorporation (COI)',
      'Memorandum & Articles of Association (MOA/AOA)',
      'Company PAN & TAN Cards',
      'DIN for 3 Directors',
      'DSC for 3 Directors',
    ],
    faqs: [
      { question: 'Is a Public Limited Company required to hold an Annual General Meeting?', answer: 'Yes, public companies must hold an AGM annually and submit audited balance sheets to the ROC.' },
    ],
  },
  {
    title: 'One Person Company(OPC)',
    slug: 'one-person-company',
    description: 'Register an OPC to secure company status with a single director/shareholder.',
    icon: '/assets/bookkepping-2.svg',
    link: '/services/one-person-company',
    order: 36,
    isActive: true,
    serviceType: 'startup',
    timeline: '7-10 working days',
    governmentFee: 1200,
    professionalFee: 5000,
    detailedOverview:
      'A One Person Company (OPC) is a corporate structure that allows a sole entrepreneur to operate a corporate entity with limited liability. It requires only 1 director and 1 nominee. Shree Chamunda Associates manages SPICe+ MCA filing, nominee consent registration, DIN allocation, name approval, and certificate of incorporation.',
    eligibility: [
      '1 Director (must be Indian resident and citizen)',
      '1 Nominee member who takes over in case of death/disability',
      'A unique company name',
    ],
    keyBenefits: [
      'Limited liability protection of a corporation for a single owner',
      'Lesser compliances compared to a Private Limited Company',
      'Easy conversion to a Private Limited Company as business grows',
    ],
    processSteps: [
      { step: 1, title: 'Name Reservation', description: 'Submit name reservation application on the MCA portal.' },
      { step: 2, title: 'DSC Procurement', description: 'Get digital signatures for director and nominee.' },
      { step: 3, title: 'SPICe+ Incorporation Filing', description: 'File the incorporation documents along with nominee consent forms.' },
      { step: 4, title: 'COI & Tax IDs', description: 'Obtain Certificate of Incorporation along with PAN & TAN.' },
    ],
    documentsRequired: [
      'PAN Card of Director & Nominee',
      'Aadhaar Card of Director & Nominee',
      'Identity & Address Proof of Director & Nominee',
      'Registered office utility bill',
      'Rent agreement & NOC',
    ],
    deliverables: [
      'Certificate of Incorporation (COI)',
      'e-MOA & e-AOA',
      'Company PAN & TAN Cards',
      'DSC for 1 Director & Nominee',
    ],
    faqs: [
      { question: 'Can a person incorporate more than one OPC?', answer: 'No. An Indian citizen and resident is only allowed to incorporate one OPC at a time.' },
    ],
  },
  {
    title: 'Partnership Firm',
    slug: 'partnership-firm',
    description: 'Register a Partnership Firm to start a co-owned business with a signed partnership deed.',
    icon: '/assets/bookkepping-2.svg',
    link: '/services/partnership-firm',
    order: 37,
    isActive: true,
    serviceType: 'startup',
    timeline: '5-8 working days',
    governmentFee: 500,
    professionalFee: 3000,
    detailedOverview:
      'A Partnership Firm is formed when two or more persons agree to share the profits of a business. It is governed by the Indian Partnership Act 1932. Shree Chamunda Associates drafts the partnership deed, executes it on stamp paper, registers it with the Registrar of Firms (ROF) in Gujarat, and obtains the firm\'s PAN card.',
    eligibility: [
      'Minimum 2 Partners',
      'A signed Partnership Deed defining profit/loss ratios',
      'Maximum limit of 50 partners',
    ],
    keyBenefits: [
      'Easy to set up and manage with a signed deed',
      'Lowest setup cost for co-owned businesses',
      'Decision-making shared among partners',
    ],
    processSteps: [
      { step: 1, title: 'Deed Drafting', description: 'We draft the partnership deed defining partner roles and shares.' },
      { step: 2, title: 'Deed Execution', description: 'Partners execute the deed on a stamp paper of appropriate value.' },
      { step: 3, title: 'ROF Filing', description: 'We submit registration application with the Registrar of Firms.' },
      { step: 4, title: 'PAN Application', description: 'We apply for a separate firm PAN card on NSDL.' },
    ],
    documentsRequired: [
      'PAN & Aadhaar of all Partners',
      'Partners Address Proof (Utility bill / Bank statement)',
      'Office Address Proof (Electricity bill / Rent agreement)',
      'NOC from property owner',
      'Partnership deed executed on stamp paper',
    ],
    deliverables: [
      'Partnership Deed Draft',
      'NSDL Firm PAN Card',
      'Registrar of Firms (ROF) Registration Certificate',
    ],
    faqs: [
      { question: 'Is ROF registration mandatory for partnerships?', answer: 'Registration with ROF is not legally mandatory, but unregistered firms cannot file lawsuits against third parties or partners in court.' },
    ],
  },
  {
    title: 'E-commerce Business',
    slug: 'e-commerce-business',
    description: 'Start selling online through Amazon, Flipkart, or your own Shopify store with GSTIN and business setup.',
    icon: '/assets/bookkepping-2.svg',
    link: '/services/e-commerce-business',
    order: 38,
    isActive: true,
    serviceType: 'startup',
    timeline: '5-7 working days',
    governmentFee: 0,
    professionalFee: 2499,
    detailedOverview:
      'Selling goods or services online requires a structural business setup (Pvt Ltd, LLP, or Proprietorship) along with compulsory GST registration. Shree Chamunda Associates sets up your legal structure, obtains your GSTIN, registers your trademark, and helps you configure business payment gateways.',
    eligibility: [
      'Any individual or entity starting an online retail, logistics, or digital marketplace business',
    ],
    keyBenefits: [
      'Compulsory GST registration handled seamlessly',
      'Legal structure optimized for marketplace onboarding (Amazon/Flipkart)',
      'Brand protection through trademark application',
    ],
    processSteps: [
      { step: 1, title: 'Business Structure Setup', description: 'We set up a proprietorship, company, or LLP.' },
      { step: 2, title: 'GST Registration', description: 'We register the business for GST, which is mandatory for e-commerce.' },
      { step: 3, title: 'Bank Account Setup', description: 'We open a current bank account for digital transactions.' },
      { step: 4, title: 'Brand Trademark', description: 'We file a trademark application to protect your brand name online.' },
    ],
    documentsRequired: [
      'Aadhaar & PAN of founders',
      'Office premises address proof',
      'Bank current account statement/cancelled cheque',
      'Owner NOC (if rented)',
    ],
    deliverables: [
      'Business Incorporation Certificate',
      'GST Registration Certificate',
      'Trademark Application copy',
      'Payment Gateway integration guide',
    ],
    faqs: [
      { question: 'Is GST mandatory for selling on Amazon?', answer: 'Yes, under GST laws, any supplier selling goods via e-commerce operators must obtain compulsory GST registration regardless of turnover.' },
    ],
  },
];

module.exports = startupServices;
